/**
 * Flight report: turn a prepared transaction, its simulation, the risk
 * findings, and the plain-language explanation into one shareable
 * markdown document. Users copy it for their records, support tickets,
 * or team review.
 *
 * Pure and deterministic: same input in, same string out. No I/O, no
 * globals, no clock — the caller supplies `generatedAt`.
 */

import type {
  Explanation,
  Hex,
  PostFlightCheck,
  PreparedTx,
  RiskFinding,
  RiskSeverity,
  SimulationResult,
} from './types';

const SEVERITY_PREFIX: Record<RiskSeverity, string> = {
  danger: '[DANGER]',
  caution: '[CAUTION]',
  info: '[INFO]',
};

const FOOTER =
  'Generated by Monad PreFlight — a simulation is a best-effort preview of chain state at the time, not a guarantee.';

const VERDICT_MATCHED = 'Verdict: everything we checked on chain matched the simulation.';
const VERDICT_MISMATCHED =
  'Verdict: some results on chain did not match the simulation — look at the rows marked ✗.';

/** One clean line of text: fold any newlines into spaces, trim the ends. */
function oneLine(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

/** Table cells additionally need their pipes escaped so rows stay intact. */
function tableCell(text: string): string {
  return oneLine(text).replace(/\|/g, '\\|');
}

/**
 * Render the full flight report as markdown.
 *
 * Sections appear in a fixed order; optional sections (warnings,
 * post-flight verification, transaction hash, explorer link) are
 * omitted entirely when there is nothing to show. The output never
 * ends with a newline and no line carries trailing whitespace.
 */
export function flightReportMarkdown(input: {
  networkLabel: string;
  tx: PreparedTx;
  sim: SimulationResult;
  risks: RiskFinding[];
  explanation: Explanation;
  postflight?: PostFlightCheck | null;
  hash?: Hex | null;
  explorerHref?: string | null;
  generatedAt: string;
}): string {
  const blocks: string[] = [];

  // Title: what this transaction does, then where and when we checked it.
  blocks.push(`# ${oneLine(input.tx.summary)}`);
  blocks.push(`${oneLine(input.networkLabel)} — ${oneLine(input.generatedAt)}`);

  // What the simulation showed.
  blocks.push('## What the simulation showed');
  blocks.push(oneLine(input.explanation.outcome));
  if (input.explanation.bullets.length > 0) {
    blocks.push(input.explanation.bullets.map((b) => `- ${oneLine(b)}`).join('\n'));
  }

  // Warnings — only when the risk check actually found something.
  if (input.risks.length > 0) {
    blocks.push('## Warnings');
    blocks.push(
      input.risks
        .map((r) => `- ${SEVERITY_PREFIX[r.severity]} ${oneLine(r.title)} — ${oneLine(r.detail)}`)
        .join('\n'),
    );
  }

  // Post-flight verification — only after the transaction has landed.
  if (input.postflight) {
    blocks.push('## Post-flight verification');
    blocks.push(
      [
        '| Check | Simulated | Actual | Match |',
        '| --- | --- | --- | --- |',
        ...input.postflight.lines.map(
          (l) =>
            `| ${tableCell(l.label)} | ${tableCell(l.simulated)} | ${tableCell(l.actual)} | ${
              l.matched ? '✓' : '✗'
            } |`,
        ),
      ].join('\n'),
    );
    blocks.push(input.postflight.matched ? VERDICT_MATCHED : VERDICT_MISMATCHED);
  }

  // On-chain references, when we have them.
  if (input.hash) {
    blocks.push(`Transaction hash: \`${input.hash}\``);
  }
  if (input.explorerHref) {
    blocks.push(`[View this transaction on the block explorer](${oneLine(input.explorerHref)})`);
  }

  blocks.push(FOOTER);

  // Drop empty blocks so the report never contains stray blank sections,
  // then join with exactly one blank line between blocks. No trailing
  // newline, no trailing whitespace on any line.
  return blocks.filter((b) => b.length > 0).join('\n\n');
}
