import { describe, expect, it } from 'vitest';

import type {
  Address,
  Explanation,
  Hex,
  PostFlightCheck,
  PreparedTx,
  RiskFinding,
  SimulationResult,
} from '../src/lib/types';
import { flightReportMarkdown } from '../src/lib/report';

/* ------------------------------------------------------------------ */
/* Fixtures                                                            */
/* ------------------------------------------------------------------ */

const USER: Address = '0x1111111111111111111111111111111111111111';
const RECIPIENT: Address = '0x123400000000000000000000000000000000abcd';

const HASH: Hex = '0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
const EXPLORER = 'https://testnet.monadexplorer.com/tx/' + HASH;

const GENERATED_AT = '2026-07-26 09:15 UTC';

function makeTx(over: Partial<PreparedTx> = {}): PreparedTx {
  return {
    from: USER,
    to: RECIPIENT,
    data: '0x',
    value: 500_000_000_000_000_000n,
    kind: 'native-transfer',
    summary: 'Send 0.5 MON to 0x1234…abcd',
    ...over,
  };
}

function makeSim(over: Partial<SimulationResult> = {}): SimulationResult {
  return {
    ok: true,
    gasUsed: 21_000n,
    gasCostWei: 2_100_000_000_000_000n,
    assetChanges: [],
    approvalChanges: [],
    events: [],
    frames: [],
    notes: [],
    ...over,
  };
}

const EXPLANATION: Explanation = {
  headline: 'You are about to send 0.5 MON',
  outcome: 'The simulation ran this transaction against the current network state and it went through without any problem.',
  bullets: ['You send 0.5 MON to 0x1234…abcd', 'Estimated network fee: 0.0021 MON'],
};

const RISKS: RiskFinding[] = [
  {
    id: 'unlimited-approval',
    severity: 'danger',
    title: 'Unlimited spending permission',
    detail: 'This lets the other contract move all of this token from your wallet, now or later.',
  },
  {
    id: 'fresh-address',
    severity: 'caution',
    title: 'Recipient looks brand new',
    detail: 'This address has never sent a transaction. Double-check you typed it correctly.',
  },
  {
    id: 'first-time-token',
    severity: 'info',
    title: 'First time using this token',
    detail: 'You have not interacted with this token before.',
  },
];

const POSTFLIGHT_MIXED: PostFlightCheck = {
  matched: false,
  lines: [
    { label: 'Outcome', simulated: 'will succeed', actual: 'succeeded', matched: true },
    { label: 'tUSD movement', simulated: 'you sent 10 tUSD', actual: 'you sent 9 tUSD', matched: false },
  ],
};

const POSTFLIGHT_CLEAN: PostFlightCheck = {
  matched: true,
  lines: [{ label: 'Outcome', simulated: 'will succeed', actual: 'succeeded', matched: true }],
};

const FOOTER =
  'Generated by Monad PreFlight — a simulation is a best-effort preview of chain state at the time, not a guarantee.';

function fullReport(): string {
  return flightReportMarkdown({
    networkLabel: 'Monad Testnet',
    tx: makeTx(),
    sim: makeSim(),
    risks: RISKS,
    explanation: EXPLANATION,
    postflight: POSTFLIGHT_MIXED,
    hash: HASH,
    explorerHref: EXPLORER,
    generatedAt: GENERATED_AT,
  });
}

function minimalReport(): string {
  return flightReportMarkdown({
    networkLabel: 'Monad Testnet',
    tx: makeTx(),
    sim: makeSim(),
    risks: [],
    explanation: EXPLANATION,
    generatedAt: GENERATED_AT,
  });
}

/* ------------------------------------------------------------------ */
/* Tests                                                               */
/* ------------------------------------------------------------------ */

describe('flightReportMarkdown — full report', () => {
  it('renders every section in order', () => {
    const md = fullReport();
    const markers = [
      '# Send 0.5 MON to 0x1234…abcd',
      'Monad Testnet — 2026-07-26 09:15 UTC',
      '## What the simulation showed',
      EXPLANATION.outcome,
      '- You send 0.5 MON to 0x1234…abcd',
      '## Warnings',
      '## Post-flight verification',
      '| Check | Simulated | Actual | Match |',
      'Transaction hash: `' + HASH + '`',
      '](' + EXPLORER + ')',
      FOOTER,
    ];
    let last = -1;
    for (const marker of markers) {
      const at = md.indexOf(marker);
      expect(at, `expected to find: ${marker}`).toBeGreaterThan(last);
      last = at;
    }
  });

  it('starts with the transaction summary as an H1', () => {
    expect(fullReport().startsWith('# Send 0.5 MON to 0x1234…abcd\n')).toBe(true);
  });

  it('renders each explanation bullet as a list item', () => {
    const md = fullReport();
    expect(md).toContain('- You send 0.5 MON to 0x1234…abcd');
    expect(md).toContain('- Estimated network fee: 0.0021 MON');
  });

  it('prefixes warnings with the right severity tags', () => {
    const md = fullReport();
    expect(md).toContain(
      '- [DANGER] Unlimited spending permission — This lets the other contract move all of this token from your wallet, now or later.',
    );
    expect(md).toContain(
      '- [CAUTION] Recipient looks brand new — This address has never sent a transaction. Double-check you typed it correctly.',
    );
    expect(md).toContain(
      '- [INFO] First time using this token — You have not interacted with this token before.',
    );
  });

  it('renders the post-flight table with ✓/✗ per row and a mismatch verdict', () => {
    const md = fullReport();
    expect(md).toContain('| Outcome | will succeed | succeeded | ✓ |');
    expect(md).toContain('| tUSD movement | you sent 10 tUSD | you sent 9 tUSD | ✗ |');
    expect(md).toContain(
      'Verdict: some results on chain did not match the simulation — look at the rows marked ✗.',
    );
    expect(md).not.toContain('Verdict: everything we checked on chain matched the simulation.');
  });

  it('shows the matched verdict when everything lined up', () => {
    const md = flightReportMarkdown({
      networkLabel: 'Monad Testnet',
      tx: makeTx(),
      sim: makeSim(),
      risks: [],
      explanation: EXPLANATION,
      postflight: POSTFLIGHT_CLEAN,
      generatedAt: GENERATED_AT,
    });
    expect(md).toContain('| Outcome | will succeed | succeeded | ✓ |');
    expect(md).toContain('Verdict: everything we checked on chain matched the simulation.');
  });

  it('is deterministic: identical input produces the identical string', () => {
    expect(fullReport()).toBe(fullReport());
  });
});

describe('flightReportMarkdown — minimal report', () => {
  it('omits warnings, post-flight, hash, and explorer sections entirely', () => {
    const md = minimalReport();
    expect(md).not.toContain('## Warnings');
    expect(md).not.toContain('## Post-flight verification');
    expect(md).not.toContain('Transaction hash');
    expect(md).not.toContain('block explorer');
    expect(md).not.toContain('[DANGER]');
    expect(md).not.toContain('|');
  });

  it('still contains the title, context line, simulation section, and footer', () => {
    const md = minimalReport();
    expect(md).toContain('# Send 0.5 MON to 0x1234…abcd');
    expect(md).toContain('Monad Testnet — 2026-07-26 09:15 UTC');
    expect(md).toContain('## What the simulation showed');
    expect(md).toContain(EXPLANATION.outcome);
    expect(md).toContain(FOOTER);
  });

  it('treats explicit nulls the same as omitted fields', () => {
    const withNulls = flightReportMarkdown({
      networkLabel: 'Monad Testnet',
      tx: makeTx(),
      sim: makeSim(),
      risks: [],
      explanation: EXPLANATION,
      postflight: null,
      hash: null,
      explorerHref: null,
      generatedAt: GENERATED_AT,
    });
    expect(withNulls).toBe(minimalReport());
  });
});

describe('flightReportMarkdown — hygiene', () => {
  it('always ends with the footer and never with whitespace', () => {
    for (const md of [fullReport(), minimalReport()]) {
      expect(md.endsWith(FOOTER)).toBe(true);
      expect(md).not.toMatch(/\n$/);
    }
  });

  it('has no line with trailing whitespace and no blank-run gaps', () => {
    for (const md of [fullReport(), minimalReport()]) {
      for (const lineText of md.split('\n')) {
        expect(lineText).toBe(lineText.trimEnd());
      }
      expect(md).not.toContain('\n\n\n');
    }
  });

  it('escapes pipe characters inside table cells so rows stay intact', () => {
    const md = flightReportMarkdown({
      networkLabel: 'Monad Testnet',
      tx: makeTx(),
      sim: makeSim(),
      risks: [],
      explanation: EXPLANATION,
      postflight: {
        matched: true,
        lines: [{ label: 'Weird | label', simulated: 'a', actual: 'a', matched: true }],
      },
      generatedAt: GENERATED_AT,
    });
    expect(md).toContain('| Weird \\| label | a | a | ✓ |');
  });
});
